### ISSUE TITLE
error in step 3

### ISSUE THREAD

**Issue by yufeng0528** [InnaTarasyan/CryptoTrading#1]
run "php artisan vendor:publish --provider="Thujohn\Twitter\TwitterServiceProvider""
got error:
In ProviderRepository.php line 208:
                                                            
  Class 'Thujohn\Twitter\TwitterServiceProvider' not found

**Comment by InnaTarasyan** [comment]
Hello !
Thank you for your reply.

In order to fix this in your local environment, you can do the following:

Open config\app.php file, remove the
Thujohn\Twitter\TwitterServiceProvider::class from 'providers' array,
also remove the
 'Twitter' => Thujohn\Twitter\Facades\Twitter::class from 'aliases' array.

After that run 'composer update' for a new and after add them again.

If that will not work, you can also remove  "thujohn/twitter": "^2.2", from
'composer.json'
file, and run the installation of this library for a new.

I have used "https://github.com/thujohn/twitter" library to retrieve the
tweets.

So you can follow the corresponding installation rules mentioned there.

For now "CryptoTrading" project is in development phase, so thanks again
for your note, I will be grateful
if you tell me about other bugs or places for enhancement.

Best Regards,
Inna Tarasyan

**Comment by yufeng0528** [comment]
thanks a lot.
it works after run 'composer update'
i think the package 'Thujohn' is not well install

**Comment by InnaTarasyan** [comment]
You are welcome :) I am going to update the installation guide.
