### ISSUE TITLE
the css/js resource Request '127.0.0.1'

### ISSUE THREAD

**Issue by yufeng0528** [InnaTarasyan/CryptoTrading#2]
my boot script is 'php artisan serve --host=ct1.aaa.com --port=8091'
in .env file edit 'APP_URL=http://ct1.aaa.com'
then i open 'http://ct1.aaa.com/login' in browser
the first request is return OK,
but other CSS/JS return 404, all request 'http://127.0.0.1:8091', i want request 'http://ct1.aaa.com/***'
.
my web server is nginx

**Comment by InnaTarasyan** [comment]
So, the issue is that CSS/JS files fail to load when using "php artisan serve" ? 

If you are using "php artisan serve" its possible that your public folder is not being used, so please use PHP native server instead and specify the public folder as the web root.
Thus, stop artisan serve and try using PHP native server by issuing this command at the root of your Laravel project:
 php -S localhost:8091 -t public

Also, please, try clearing laravel cache, clearing browser cache, going incognito, and setting permission 777 to that folder. 

From my point of view, a more convenient way is creating a Nginx VirtualHost, instead
of running "php artisan serve". For example, if you are working on Ubuntu, this tutorials can be very
helpful:

https://www.digitalocean.com/community/tutorials/how-to-deploy-a-laravel-application-with-nginx-on-ubuntu-16-04
https://www.digitalocean.com/community/tutorials/linux-nginx-mysql-php-lemp-ubuntu-16-04-ru

**Comment by yufeng0528** [comment]
the first url works for me. Thanks
